### ISSUE TITLE
Fonts too Small

### ISSUE THREAD

**Issue by petersilva** [petersilva/drobo-utils#6]
from @oblongau
the computer this is running on has a high resolution screen (3840 x 2160) so the GUI is quite small and the text too small to be easily readable. The window can be resized but the text size does not change.
How would that be fixed? Any pointers as to where to look would be appreciated. (Should this question be given its own issue?)
Thanks.

**Comment by petersilva** [comment]
I googled a bit. drobom is built using QT5. found this: https://wiki.archlinux.org/title/HiDPI#Qt_5
based on that, I did this:


fractal% export QT_AUTO_SCREEN_SCALE_FACTOR=0
fractal% export QT_SCALE_FACTOR=2
fractal% ./drobom -v 128 view

and got a huge GUI. yeah... this should probably be a separate issue.

**Comment by petersilva** [comment]
This also works, without polluting the environment for all other QT apps you start:
fractal% QT_SCALE_FACTOR=2 ./drobom -v 128 view

**Comment by oblongau** [comment]
> This also works, without polluting the environment for all other QT apps you start: fractal% QT_SCALE_FACTOR=2 ./drobom -v 128 view

Yes, adding `QT_SCALE_FACTOR=2` into the line in `droboview `which calls `drobom `works fine. Many thanks for the solution.
